criaCartao('Cinemática', 'O que é velocidade escalar média?', 'É a razão entre o deslocamento e o intervalo de tempo.')
criaCartao('Cinemática', 'Qual a fórmula da equação horária do espaço?', 'S = S₀ + v·t.')
criaCartao('Cinemática', 'O que é aceleração escalar média?', 'É a variação da velocidade dividida pelo intervalo de tempo.')
criaCartao('Cinemática', 'O que caracteriza um movimento uniformemente variado?', 'A aceleração é constante.')
criaCartao('Dinâmica', 'Qual é a 1ª Lei de Newton?', 'Um corpo em repouso ou em movimento uniforme permanecerá assim se nenhuma força atuar sobre ele.')
criaCartao('Dinâmica', 'Qual é a 2ª Lei de Newton?', 'A força resultante é igual ao produto da massa pela aceleração: F = m·a.')
criaCartao('Dinâmica', 'Qual é a 3ª Lei de Newton?', 'Para toda ação há uma reação de mesma intensidade e direção, mas sentidos opostos.')
criaCartao('Dinâmica', 'O que é força centrípeta?', 'É a força que mantém um corpo em movimento circular.')
criaCartao('Gravitação', 'O que diz a Lei da Gravitação Universal?', 'Dois corpos se atraem com uma força proporcional ao produto de suas massas e inversamente proporcional ao quadrado da distância entre eles.')
criaCartao('Gravitação', 'Qual é a fórmula da força gravitacional?', 'F = G·(m₁·m₂)/r².')
criaCartao('Gravitação', 'O que é velocidade de escape?', 'É a velocidade mínima para um corpo escapar da gravidade de um planeta.')
criaCartao('Gravitação', 'Qual é a constante gravitacional?', 'G = 6,67 × 10⁻¹¹ N·m²/kg².')
criaCartao('Ondulatória', 'O que é frequência de uma onda?', 'É o número de oscilações por segundo.')
criaCartao('Ondulatória', 'Qual é a relação entre frequência e período?', 'f = 1/T.')
criaCartao('Ondulatória', 'O que é comprimento de onda?', 'É a distância entre dois pontos consecutivos de fase igual em uma onda.')
criaCartao('Ondulatória', 'Qual é a fórmula da velocidade de propagação de uma onda?', 'v = λ·f.')
criaCartao('Termodinâmica', 'O que é temperatura?', 'É a grandeza que mede o grau de agitação das partículas de um corpo.')
criaCartao('Termodinâmica', 'Qual é a 1ª Lei da Termodinâmica?', 'A variação da energia interna é igual ao calor trocado menos o trabalho realizado: ΔU = Q - W.')
criaCartao('Termodinâmica', 'O que é calor específico?', 'É a quantidade de calor necessária para variar a temperatura de 1g de uma substância em 1°C.')
criaCartao('Termodinâmica', 'O que é entropia?', 'É a medida da desordem de um sistema.')
criaCartao('Eletricidade', 'O que é corrente elétrica?', 'É o movimento ordenado de cargas elétricas.')
criaCartao('Eletricidade', 'Qual é a unidade de medida da corrente elétrica?', 'Ampère (A).')
criaCartao('Eletricidade', 'O que é resistência elétrica?', 'É a oposição ao fluxo de corrente em um material.')
criaCartao('Eletricidade', 'Qual é a fórmula da Lei de Ohm?', 'V = R·I.')
criaCartao('Magnetismo', 'O que é um campo magnético?', 'É a região do espaço onde atua a força magnética.')
criaCartao('Magnetismo', 'O que são polos magnéticos?', 'São as extremidades de um ímã, onde o campo magnético é mais intenso.')
criaCartao('Magnetismo', 'O que é indução eletromagnética?', 'É o fenômeno de geração de uma corrente elétrica em um condutor pela variação do campo magnético.')
criaCartao('Magnetismo', 'O que é força magnética?', 'É a força exercida por um campo magnético sobre cargas em movimento.')
criaCartao('Óptica', 'O que é refração da luz?', 'É a mudança de direção e velocidade da luz ao passar de um meio para outro.')
criaCartao('Óptica', 'O que é reflexão da luz?', 'É o retorno da luz ao meio de origem após atingir uma superfície.')
criaCartao('Óptica', 'O que é dispersão da luz?', 'É a separação da luz branca em suas cores componentes.')
criaCartao('Óptica', 'Qual é a fórmula da equação de Gauss para espelhos esféricos?', '1/f = 1/p + 1/q.')
criaCartao('Física Moderna', 'O que é o efeito fotoelétrico?', 'É a emissão de elétrons de um material ao ser iluminado.')
criaCartao('Física Moderna', 'O que é dualidade onda-partícula?', 'É o conceito de que partículas podem exibir propriedades de onda e vice-versa.')
criaCartao('Física Moderna', 'O que é fissão nuclear?', 'É o processo de divisão de um núcleo atômico pesado em dois núcleos menores.')
criaCartao('Física Moderna', 'O que é fusão nuclear?', 'É o processo de união de dois núcleos leves para formar um núcleo mais pesado.')
criaCartao('Astrofísica', 'O que são buracos negros?', 'São regiões do espaço com gravidade tão intensa que nada pode escapar, nem mesmo a luz.')
criaCartao('Astrofísica', 'O que é uma estrela?', 'É um corpo celeste que emite luz própria devido a reações nucleares em seu interior.')
criaCartao('Astrofísica', 'O que é matéria escura?', 'É uma forma de matéria que não emite radiação, mas cuja presença é inferida pelos efeitos gravitacionais.')
criaCartao('Astrofísica', 'O que é Big Bang?', 'É a teoria que descreve a origem do universo a partir de uma grande explosão.')
criaCartao('Mecânica dos Fluidos', 'O que é pressão?', 'É a força exercida por unidade de área.')
criaCartao('Mecânica dos Fluidos', 'O que é empuxo?', 'É a força vertical para cima exercida por um fluido sobre um corpo imerso.')
criaCartao('Mecânica dos Fluidos', 'Qual é a fórmula do Princípio de Arquimedes?', 'E = d·g·V.')
criaCartao('Mecânica dos Fluidos', 'O que é viscosidade?', 'É a resistência de um fluido ao escoamento.')


